import streamlit as st

st.title("Sample Prompts for Finance Bro AI")

st.write("Below is a list of questions and their corresponding answers.")

# Define questions and answers
data = [
    {"Question": "What are spreads?", "Answer": "Spreads refer to different concepts depending on the financial context: Lending: In lending, a spread is the difference between the interest rate charged on loans and the interest rate paid on deposits. It's a primary source of profit for banks and other lending institutions. Options Trading: In options trading, spreads involve strategies using multiple options contracts, such as bull spreads or butterfly spreads, which help traders manage their risk exposure. Foreign Exchange (Forex) Markets: In forex, spreads represent the difference between the buy and sell prices of currency pairs. These spreads can change based on market volatility and liquidity. Securities: The bid-ask spread is common in securities, referring to the difference between the highest price a buyer is willing to pay (bid) and the lowest price a seller will accept (ask). A narrow spread often indicates high liquidity and low transaction costs. Bond Market: In bonds, spreads measure the yield difference between two securities, such as the spread between U.S. Treasury bonds and corporate bonds of the same maturity, reflecting the additional yield investors require for taking on higher risk. Each type of spread provides insights into different aspects of financial markets and instruments."},
    {"Question": "What is a stock?", "Answer": "A stock is a type of security that represents ownership in a corporation. When you own stock in a company, you have a claim on part of the company's assets and earnings. Stocks are also known as shares or equity. Companies issue stock to raise capital for various purposes, such as expanding their operations, launching new products, or paying off debt. Investors buy stocks in the hope that they will appreciate in value over time or provide dividends, which are payments made to shareholders from the company's profits."},
    {"Question": "What is an option?", "Answer": "An option is a financial agreement that grants the buyer the right, but not the obligation, to buy or sell a particular asset, like a stock, at a preset price within a given period. This type of contract allows the holder to potentially capitalize on price changes in the underlying asset, providing leverage, managing risk, and offering strategic flexibility. Unlike futures contracts, the buyer of an options contract is not required to exercise the option to buy or sell the asset, making it an opportunity rather than an obligation."},
    {"Question": "How do I valuate an asset?", "Answer": "To value an asset, you can use one of the three approaches outlined by the generally accepted accounting principles (GAAP): Market Approach: This approach involves establishing a value based on the sale price of similar assets in the open market. It's useful when there are comparable assets that have been recently sold, providing a benchmark for valuation. Income Approach: This method predicts the future cash flows that the asset is expected to generate. These predicted cash flows are then combined into a single present value figure by applying a discount rate. This approach is well-suited for assets that generate regular income, such as rental properties or businesses. Cost Approach: This approach estimates the cost of buying or building a new asset with the same quality and utility. It considers the expenses involved in constructing a similar asset from scratch or replacing it. Choose the approach that best suits the type of asset you're valuing and the available data. For instance, for marketable securities like stocks and bonds, the market approach may be most appropriate, whereas for unique items like patents or trademarks, the income approach could be more suitable."},
    {"Question": "What are candle sticks?", "Answer": "Candlesticks are technical trading tools used in financial markets to represent price movements within a specific time period. Each candlestick on a chart provides a visual depiction of the battle between buyers and sellers during that time frame. A light candle (typically green or white) indicates that buyers have won, meaning the closing price is higher than the opening price. Conversely, a dark candle (typically red or black) indicates that sellers have dominated, meaning the closing price is lower than the opening price. Candlestick patterns have been used for centuries to predict price direction and are often supplemented with additional technical indicators to refine trading strategies."},
]
    
st.table(data)