import streamlit as st

st.title("Sample Prompts for Finance Bro AI")

st.write("Below is a list of questions and their corresponding answers.")

# Define questions and answers
data = [
    {"Question": "Hey Finance Bro, can you tell me more about what a SWOT analysis is and how do you conduct one?", "Answer": "A SWOT analysis is a framework used to evaluate a company's competitive position and to develop strategic planning. It assesses internal and external factors, as well as current and future potential. The analysis is designed to provide a realistic, fact-based, data-driven look at the strengths and weaknesses of an organization, initiatives, or its industry. To conduct a SWOT analysis, you should: Identify and analyze the strengths, weaknesses, opportunities, and threats of the company. Create a list of questions for each element to guide the analysis. This helps ensure that all relevant factors are considered. Construct the SWOT framework in one of the common formats, such as a list, free text, or a 4-cell table with quadrants dedicated to each element. Typically, you would list strengths and weaknesses first, followed by opportunities and threats. This structured approach helps in creating a balanced and comprehensive analysis."},
    {"Question": "What is a stock?", "Answer": "A stock is a type of security that represents ownership in a corporation. When you own stock in a company, you have a claim on part of the company's assets and earnings. Stocks are also known as shares or equity. Companies issue stock to raise capital for various purposes, such as expanding their operations, launching new products, or paying off debt. Investors buy stocks in the hope that they will appreciate in value over time or provide dividends, which are payments made to shareholders from the company's profits."},
    {"Question": "What is an option?", "Answer": "An option is a financial agreement that grants the buyer the right, but not the obligation, to buy or sell a particular asset, like a stock, at a preset price within a given period. This type of contract allows the holder to potentially capitalize on price changes in the underlying asset, providing leverage, managing risk, and offering strategic flexibility. Unlike futures contracts, the buyer of an options contract is not required to exercise the option to buy or sell the asset, making it an opportunity rather than an obligation."},
    {"Question": "How do I valuate an asset?", "Answer": "Asset valuation can be performed using several methods, depending on the type of asset and the available data. Here are some common approaches: \n Book Value: This is the net value of a company's assets as recorded on the balance sheet, calculated as total assets minus intangible assets and liabilities. \n Absolute Valuation Models: These models determine an asset's intrinsic value based on its characteristics. Common models include: \n\n Discounted Cash Flow (DCF) Analysis: Projects future cash flows and discounts them back to the present value. \n\n Discounted Dividend Models: Similar to DCF but focuses on future dividends. \n\n Discounted Asset Models: Values the asset based on projected income or cash flows specific to the asset. \n\n Option Pricing Models: Used for valuing options and other complex financial instruments. \n\n Relative Valuation Ratios: These involve comparing the asset to similar assets using ratios like the Price-to-Earnings (P/E) ratio. \n\n Comparables: Evaluating an asset by looking at the market value of similar assets. It often involves both subjective and objective measures, and the chosen method may vary based on the asset's nature and the context of the valuation."},
    {"Question": "What are candle sticks?", "Answer": "Candlesticks are technical trading tools used in financial markets to represent price movements within a specific time period. Each candlestick on a chart provides a visual depiction of the battle between buyers and sellers during that time frame. A light candle (typically green or white) indicates that buyers have won, meaning the closing price is higher than the opening price. Conversely, a dark candle (typically red or black) indicates that sellers have dominated, meaning the closing price is lower than the opening price. Candlestick patterns have been used for centuries to predict price direction and are often supplemented with additional technical indicators to refine trading strategies."},
]
    
st.table(data)